### PR TITLE
chore: migrate to vue 3

### PR DESCRIPTION
**Pull request by raimund-schluessler**
This migrates the package to vue 3. It basically pulls in the `beta` branch from https://github.com/sagalbot/vue-select/tree/beta onto our adjustments. However, I did that manually and fixed some issues along the way.
I did not really care to adjust the docs, but the component itself and the tests work fine.
Also, I don't have `yarn`, so someone who has it installed needs to create the `yarn.lock` file. Or we just migrate to `npm`, which might be better anyway.

I tested the library in the `nextcloud/vue` docs vue 3 branch, and it works just fine as far as I can tell.

Of course, we wouldn't merge into `master` yet, but since I don't have the appropriate rights here, I couldn't create any branch here.

### CODE REVIEW

**Comment by GretaD** [comment]
+1 to migrate to npm

**Comment by Pytal** [comment]
Rights granted @raimund-schluessler :)

**Comment by Pytal** [comment]
Also might make sense to use something like https://github.com/vueuse/vue-demi for single branch maintenance

**Comment by raimund-schluessler** [comment]
> Also might make sense to use something like https://github.com/vueuse/vue-demi for single branch maintenance

Not sure about this. Vue 2 will be EOL in 3 months, so the better solution is to migrate to Vue 3 and drop support for 2 completely, I think.

**Comment by raimund-schluessler** [comment]
> Rights granted @raimund-schluessler :)

Thanks. How should we proceed here? Should I create a `next` branch from `master` and create a PR against it, as we do it in the nextcloud/vue repo?

**Comment by Pytal** [comment]
> Thanks. How should we proceed here? Should I create a `next` branch from `master` and create a PR against it, as we do it in the nextcloud/vue repo?

Precisely :)

**Comment by raimund-schluessler** [comment]
Closed in favor of #25.

**Pull request closed without merging**
